version: 2
jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Install python, pip, and the AWS EB CLI
          command: |
            sudo apt update
            sudo apt install -y python-pip python-dev
            sudo pip install awsebcli
      - run:
          name: Deploying
          command: eb deploy YourMd-env

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - staging
                - master
