version: 2
jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout

      - run:
          name: Install python, pip, and the AWS EB CLI
          command: |
            sudo apt-get install python-pip python-dev
            sudo pip install awsebcli==3.14.11
      - run:
          name: Deploying
          command: eb deploy $CIRCLE_BRANCH-YOUR-MD

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - staging
                - master
